#Refines refined.csv by making a new copy without default room names, entitled descriptionSort.csv


import pandas as pd
bannedDescriptions = ["This template is part of the RoomSetup101 tutorial. This room teaches you how to create, save, and publish your room! By publishing your room other players from all over the world will be able to experience what you have created.",
                      "Looking to start your own creator class or workshop? This Template contains a ready-made setup of Maker Pen Roles that will help moderate griefing in your very own creator class or workshop.",
                      "Create your own PVP using this template!\nThis template has Beta Content enabled. Some contents are experimental and subject to change. You cannot create inventions in rooms that have Beta Content enabled.",
                      "A Cozy Clubhouse template to chill in with your community! ",
                      "A Quest Action clubhouse template to enjoy with your community!",
                      "A Spooky Clubhouse template to chill in with your community! ",
                      "Create your own PVP using this template!\n\nThis template has Beta Content enabled. Some contents are experimental and subject to change. You cannot create inventions in rooms that have Beta Content enabled.",
                      "Relax on the warm beach and swim in the ocean. You can customize this template however you like.",
                      "Create your own wedding by customizing this template however you like!",
                      "Show off your style on your very own catwalk. You can customize this template however you like.",
                      "Open and ready for business. Sell your inventions in this modern themed store. You can customize this template however you like.",
                      "A cozy event venue with a stage. The entire room is made of props, so customize to your heart's content!",
                      "Open and ready for business. Sell your inventions in this cozy themed store. You can customize this template however you like.",
                      "This template is perfect for birthdays, parties and celebrations. Customize the venue however you like.",
                      "This template is perfect for meetings, classes, or just hanging out. The room contains several outdoor meeting areas that are easily customizable.",
                      "This is a template! Hangout with your friends and create your own ski slopes!",
                      "Use this template to create your very own Stunt Runner course! Includes everything you need to get started!",
                      "A soundstage warehouse used to film Stunt Runner and other RecTV shows.",
                      "This is a great template if you are looking to create a costume, host an event, put on a show, or just hang out with your friends!",
                      "Put together your own theme, hang out with your community, celebrate your goals, give out prizes, put on your own talk shows, and hang out with your fans! Make it into whatever you like!",
                      "Thank you @Depressed_Apple, and @Noctauto for the help!",
                      "Lone Shoe Lanes is the hottest hangout in town. ",
                      "A late-2080s-style cyberpunk dystopian laser tag battle arcade",
                      "A late-eighties-style laser tag battle arcade.",
                      "A professional stadium for larger sporting events.",
                      "A school gymnasium for smaller sporting events.",
                      "The science department left some of their equipment laying around. What will you do with it?",
                      "A leisurely trail to the lake and beyond.",
                      "Night shift as the hydroelectric plant. Great for stealthy splatting!",
                      "The sun rises on this logging camp in the forest. Great for mid-range splatting!",
                      "The sun sets on this construction site in the desert. Great for sniping battles!",
                      "A day on the farm. Great for asymmetrical battles!",
                      "The original outdoor paintball course. Simple, balanced, classic.",
                      "A theater for plays, music, comedy and other performances.",
                      "A low-key lounge to chill with your friends. Great for private parties!",
                      "A six-player off-road rally race where you boost, bump, and powerslide your way to the finish line!",
                      "Gather your vampire hunting crew, conquer a legendary castle, and restore peace to Rec Room!",
                      "A simple rally game between two players in a plexiglass tube with a zero-g ball.",
                      "Red and Blue teams splat each other in capture the flag and team battle.",
                      "The goblin king stole Coach's Golden Trophy. Team up and embark on an epic quest to recover it!",
                      "Robot invaders threaten the galaxy! Team up with your friends and bring the laser heat!",
                      "Can your band of adventurers brave the enchanted wilds, and lift the curse of the crimson cauldron?",
                      "Can your pirate crew get to the Isle, defeat its fearsome guardian, and escape with the gold?",
                      "Teams of three run around slamming themselves into an over-sized soccer ball. Goal!",
                      "Teams battle each other and waves of robots.",
                      "Take turns drawing, acting, and guessing funny phrases with your friends!",
                      "Hang out with friends, bowl a few games, eat snacks!",
                      "Throw dodgeballs to knock out your friends in this gym classic!",
                      "Take turns drawing, acting, and guessing funny phrases with your friends!",
                      "A leisurely stroll through the grass. Throw your disc into the goal. Sounds easy, right?",
                      "Throw your disc through hazards and around wind machines on this challenging course!",
                      "RecCon 2023 is October 5th - 8th. You can clone this room to make your own RecCon event!",
                      "Performance Hall",
                      "This room is a blank canvas. Make it into whatever you like!",
                      "A sprawling park with amphitheater, play fields, and a cave.",
                      " Put on a talk Show, Stand Up, or Create Movies!",
                      "Maker Room",
                      "Use this room to create your own PvP! Thanks to @Ryukiin for the help on the Circuits!"]

df = pd.read_csv('refined.csv', low_memory = False)
ndf = df[~df['description'].isin(bannedDescriptions)]
ndf.to_csv('descriptionSort.csv', mode = 'w', index = False)
print(str(len(ndf)))
